### ISSUE TITLE
Accesso diretto per tg789vac xtream 35b

### ISSUE THREAD

**Issue by viaggio32** [FrancYescO/tch_firmware_extracted#1]
Ciao, scusa se ti scrivo anche qui.
Ti potrebbe fare comodo l'accesso diretto (web e ssh) al modem? Non svolge nessuna operazione e non ho problemi a renderlo visibile esternamente.

**Comment by FrancYescO** [comment]
probabilmente facciamo prima..
passami i dati in pm su ilpuntotecnico o http://t.me/francyesc0

**Comment by FrancYescO** [comment]
o se vuoi anche qui poi elimino la issue...

**Comment by viaggio32** [comment]
Se per te va bene ti scrivo su telegram, il tempo di preparare il modem
